CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  login VARCHAR(80) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT users_login_unique UNIQUE (login),
  CONSTRAINT users_role_check CHECK (role IN ('admin', 'gestor', 'estoquista'))
);

CREATE TABLE IF NOT EXISTS ocs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(20) NOT NULL,
  gestor_id INTEGER NOT NULL,
  estoquista_id INTEGER NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'aberta',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ocs_codigo_unique UNIQUE (codigo),
  CONSTRAINT ocs_gestor_id_fk FOREIGN KEY (gestor_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ocs_estoquista_id_fk FOREIGN KEY (estoquista_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT ocs_status_check CHECK (status IN ('aberta', 'aguardando_aprovacao', 'finalizada'))
);

CREATE TABLE IF NOT EXISTS oc_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oc_id INTEGER NOT NULL,
  produto VARCHAR(255) NOT NULL,
  saldo_sistema DOUBLE PRECISION NOT NULL,
  saldo_contado DOUBLE PRECISION,
  lote VARCHAR(80),
  diferenca DOUBLE PRECISION,
  status VARCHAR(40) NOT NULL DEFAULT 'pendente',
  endereco VARCHAR(120),
  codigo VARCHAR(80),
  codigo_barras VARCHAR(80),
  validade DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT oc_items_oc_id_fk FOREIGN KEY (oc_id) REFERENCES ocs (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT oc_items_status_check CHECK (status IN ('pendente', 'contado', 'aprovado', 'recontar'))
);

CREATE TABLE IF NOT EXISTS contagens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oc_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  quantidade DOUBLE PRECISION NOT NULL,
  lote VARCHAR(80) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT contagens_oc_id_fk FOREIGN KEY (oc_id) REFERENCES ocs (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT contagens_item_id_fk FOREIGN KEY (item_id) REFERENCES oc_items (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);
CREATE INDEX IF NOT EXISTS idx_ocs_gestor_id ON ocs (gestor_id);
CREATE INDEX IF NOT EXISTS idx_ocs_estoquista_id ON ocs (estoquista_id);
CREATE INDEX IF NOT EXISTS idx_ocs_status ON ocs (status);
CREATE INDEX IF NOT EXISTS idx_oc_items_oc_id ON oc_items (oc_id);
CREATE INDEX IF NOT EXISTS idx_oc_items_status ON oc_items (status);
CREATE INDEX IF NOT EXISTS idx_contagens_oc_id ON contagens (oc_id);
CREATE INDEX IF NOT EXISTS idx_contagens_item_id ON contagens (item_id);
