CREATE TABLE IF NOT EXISTS empresas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(40) NOT NULL UNIQUE,
  nome VARCHAR(120) NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_empresas (
  user_id INTEGER NOT NULL REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
  empresa_id INTEGER NOT NULL REFERENCES empresas (id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, empresa_id)
);

CREATE INDEX IF NOT EXISTS idx_user_empresas_user_id ON user_empresas (user_id);
CREATE INDEX IF NOT EXISTS idx_user_empresas_empresa_id ON user_empresas (empresa_id);
CREATE INDEX IF NOT EXISTS idx_empresas_codigo ON empresas (codigo);
CREATE INDEX IF NOT EXISTS idx_empresas_ativo ON empresas (ativo);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname = 'set_updated_at'
      AND pg_get_function_identity_arguments(p.oid) = ''
  ) THEN
    CREATE FUNCTION set_updated_at()
    RETURNS TRIGGER AS $function$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $function$ LANGUAGE plpgsql;
  END IF;
END
$$;

DROP TRIGGER IF EXISTS trg_empresas_set_updated_at ON empresas;
CREATE TRIGGER trg_empresas_set_updated_at
BEFORE UPDATE ON empresas
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

INSERT INTO empresas (codigo, nome)
VALUES
  ('DIMEBRAS_PR', 'Dimebras PR'),
  ('DIMEBRAS_SC', 'Dimebras SC'),
  ('DIMEBRAS_MT', 'Dimebras MT'),
  ('DIMEBRAS_MS', 'Dimebras MS'),
  ('ALFAMED_MS', 'Alfamed MS')
ON CONFLICT (codigo) DO UPDATE
SET
  nome = EXCLUDED.nome,
  ativo = true;

INSERT INTO user_empresas (user_id, empresa_id)
SELECT users.id, empresas.id
FROM users
CROSS JOIN empresas
ON CONFLICT DO NOTHING;
