DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM empresas
    WHERE id IN (1, 2, 3, 5, 6)
      AND codigo NOT IN (
        'DIMEBRAS_PR',
        'ALFAMED_MS',
        'DIMEBRAS_MT',
        'DIMEBRAS_MS',
        'DIMEBRAS_SC'
      )
  ) THEN
    UPDATE empresas
    SET id = -200000 - id
    WHERE id IN (1, 2, 3, 5, 6)
      AND codigo NOT IN (
        'DIMEBRAS_PR',
        'ALFAMED_MS',
        'DIMEBRAS_MT',
        'DIMEBRAS_MS',
        'DIMEBRAS_SC'
      );
  END IF;
END
$$;

INSERT INTO empresas (id, codigo, nome, ativo)
VALUES
  (-100001, 'DIMEBRAS_PR', 'Dimebras PR', true),
  (-100002, 'ALFAMED_MS', 'Alfamed MS', true),
  (-100003, 'DIMEBRAS_MT', 'Dimebras MT', true),
  (-100005, 'DIMEBRAS_MS', 'Dimebras MS', true),
  (-100006, 'DIMEBRAS_SC', 'Dimebras SC', true)
ON CONFLICT (codigo) DO NOTHING;

UPDATE empresas
SET id = CASE codigo
    WHEN 'DIMEBRAS_PR' THEN -100001
    WHEN 'ALFAMED_MS' THEN -100002
    WHEN 'DIMEBRAS_MT' THEN -100003
    WHEN 'DIMEBRAS_MS' THEN -100005
    WHEN 'DIMEBRAS_SC' THEN -100006
  END,
  nome = CASE codigo
    WHEN 'DIMEBRAS_PR' THEN 'Dimebras PR'
    WHEN 'ALFAMED_MS' THEN 'Alfamed MS'
    WHEN 'DIMEBRAS_MT' THEN 'Dimebras MT'
    WHEN 'DIMEBRAS_MS' THEN 'Dimebras MS'
    WHEN 'DIMEBRAS_SC' THEN 'Dimebras SC'
  END,
  ativo = true
WHERE codigo IN (
  'DIMEBRAS_PR',
  'ALFAMED_MS',
  'DIMEBRAS_MT',
  'DIMEBRAS_MS',
  'DIMEBRAS_SC'
);

UPDATE empresas
SET id = CASE codigo
    WHEN 'DIMEBRAS_PR' THEN 1
    WHEN 'ALFAMED_MS' THEN 2
    WHEN 'DIMEBRAS_MT' THEN 3
    WHEN 'DIMEBRAS_MS' THEN 5
    WHEN 'DIMEBRAS_SC' THEN 6
  END
WHERE codigo IN (
  'DIMEBRAS_PR',
  'ALFAMED_MS',
  'DIMEBRAS_MT',
  'DIMEBRAS_MS',
  'DIMEBRAS_SC'
);

CREATE TABLE IF NOT EXISTS oc_produtos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oc_id INTEGER NOT NULL,
  produto_externo_id VARCHAR(120),
  codigo VARCHAR(80),
  codigo_barras VARCHAR(80),
  descricao_snapshot VARCHAR(255) NOT NULL,
  saldo_sistema_snapshot NUMERIC(12,3) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pendente',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT oc_produtos_oc_id_fk FOREIGN KEY (oc_id) REFERENCES ocs (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT oc_produtos_status_check CHECK (status IN ('pendente', 'contado', 'aprovado', 'recontar'))
);

CREATE TABLE IF NOT EXISTS oc_localizacoes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oc_produto_id INTEGER NOT NULL,
  localizacao_externa_id VARCHAR(120),
  endereco_snapshot VARCHAR(120) NOT NULL,
  codigo_barras_snapshot VARCHAR(80),
  validade_snapshot DATE,
  status VARCHAR(40) NOT NULL DEFAULT 'pendente',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT oc_localizacoes_oc_produto_id_fk FOREIGN KEY (oc_produto_id) REFERENCES oc_produtos (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT oc_localizacoes_status_check CHECK (status IN ('pendente', 'contado', 'recontar'))
);

CREATE TABLE IF NOT EXISTS oc_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oc_id INTEGER NOT NULL,
  ciclo INTEGER NOT NULL,
  fase VARCHAR(40) NOT NULL,
  estoquista_id INTEGER NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'ativo',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finalizado_em TIMESTAMPTZ,
  CONSTRAINT oc_assignments_oc_id_fk FOREIGN KEY (oc_id) REFERENCES ocs (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT oc_assignments_estoquista_id_fk FOREIGN KEY (estoquista_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT oc_assignments_ciclo_check CHECK (ciclo > 0),
  CONSTRAINT oc_assignments_fase_check CHECK (fase IN ('contagem', 'recontagem')),
  CONSTRAINT oc_assignments_status_check CHECK (status IN ('ativo', 'pendente', 'em_andamento', 'finalizado', 'cancelado')),
  CONSTRAINT oc_assignments_oc_id_ciclo_unique UNIQUE (oc_id, ciclo)
);

ALTER TABLE contagens
  ADD COLUMN IF NOT EXISTS oc_produto_id INTEGER,
  ADD COLUMN IF NOT EXISTS oc_localizacao_id INTEGER,
  ADD COLUMN IF NOT EXISTS assignment_id INTEGER;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'contagens_oc_produto_id_fk'
  ) THEN
    ALTER TABLE contagens
      ADD CONSTRAINT contagens_oc_produto_id_fk
      FOREIGN KEY (oc_produto_id)
      REFERENCES oc_produtos (id)
      ON UPDATE CASCADE
      ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'contagens_oc_localizacao_id_fk'
  ) THEN
    ALTER TABLE contagens
      ADD CONSTRAINT contagens_oc_localizacao_id_fk
      FOREIGN KEY (oc_localizacao_id)
      REFERENCES oc_localizacoes (id)
      ON UPDATE CASCADE
      ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'contagens_assignment_id_fk'
  ) THEN
    ALTER TABLE contagens
      ADD CONSTRAINT contagens_assignment_id_fk
      FOREIGN KEY (assignment_id)
      REFERENCES oc_assignments (id)
      ON UPDATE CASCADE
      ON DELETE SET NULL;
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_oc_produtos_oc_id_produto_externo_id_unique
  ON oc_produtos (oc_id, produto_externo_id)
  WHERE produto_externo_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_oc_produtos_oc_id_codigo_unique
  ON oc_produtos (oc_id, codigo)
  WHERE produto_externo_id IS NULL AND codigo IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_oc_produtos_oc_id ON oc_produtos (oc_id);
CREATE INDEX IF NOT EXISTS idx_oc_produtos_status ON oc_produtos (status);
CREATE INDEX IF NOT EXISTS idx_oc_produtos_codigo ON oc_produtos (codigo);

CREATE UNIQUE INDEX IF NOT EXISTS idx_oc_localizacoes_produto_localizacao_externa_unique
  ON oc_localizacoes (oc_produto_id, localizacao_externa_id)
  WHERE localizacao_externa_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_oc_localizacoes_produto_endereco_unique
  ON oc_localizacoes (oc_produto_id, endereco_snapshot)
  WHERE localizacao_externa_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_oc_localizacoes_oc_produto_id ON oc_localizacoes (oc_produto_id);
CREATE INDEX IF NOT EXISTS idx_oc_localizacoes_status ON oc_localizacoes (status);

CREATE INDEX IF NOT EXISTS idx_oc_assignments_oc_id ON oc_assignments (oc_id);
CREATE INDEX IF NOT EXISTS idx_oc_assignments_estoquista_id ON oc_assignments (estoquista_id);
CREATE INDEX IF NOT EXISTS idx_oc_assignments_status ON oc_assignments (status);

CREATE INDEX IF NOT EXISTS idx_contagens_oc_produto_id ON contagens (oc_produto_id);
CREATE INDEX IF NOT EXISTS idx_contagens_oc_localizacao_id ON contagens (oc_localizacao_id);
CREATE INDEX IF NOT EXISTS idx_contagens_assignment_id ON contagens (assignment_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_contagens_assignment_localizacao_unique
  ON contagens (assignment_id, oc_localizacao_id)
  WHERE assignment_id IS NOT NULL
    AND oc_localizacao_id IS NOT NULL;

DROP TRIGGER IF EXISTS trg_oc_produtos_set_updated_at ON oc_produtos;
CREATE TRIGGER trg_oc_produtos_set_updated_at
BEFORE UPDATE ON oc_produtos
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_oc_localizacoes_set_updated_at ON oc_localizacoes;
CREATE TRIGGER trg_oc_localizacoes_set_updated_at
BEFORE UPDATE ON oc_localizacoes
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DO $$
DECLARE
  seq_name TEXT;
BEGIN
  seq_name := pg_get_serial_sequence('empresas', 'id');

  IF seq_name IS NOT NULL THEN
    EXECUTE format(
      'SELECT setval(%L, (SELECT GREATEST(COALESCE(MAX(id), 0), 1) FROM empresas), true)',
      seq_name
    );
  END IF;
END
$$;
